// This is a WORKER - Workers are tasks with a dedicated rx_channel
//
// Messenger is responsible for communicating whith other nodes.
// After proper processing, relevant events generated by the client
// will end up here, the last step before entering into TCP domain.

use anyhow::{Context, bail};
use core::{AnyResult, NimbusProtocol, errors::client_err::WorkerError};
use tokio::{self, io::AsyncWriteExt, net::TcpStream, sync::mpsc::Receiver, task::JoinHandle};

type NimbusReceiver = Receiver<NimbusProtocol>;

pub async fn spawn_messenger(
    mut internal_network_rx: NimbusReceiver,
    mut tcp_stream: TcpStream,
) -> JoinHandle<AnyResult<()>> {
    tokio::spawn(async move {
        // Listenn and sends via tcp
        while let Some(nimbus_protocol) = internal_network_rx.recv().await {
            if let Ok(encoded) = nimbus_protocol.encode() {
                if let Err(e) = tcp_stream.write_all(&encoded[..]).await {
                    println!("");
                    println!("Failed to write in tcp stream");
                    println!("{:?}", e);
                    println!("");
                };
            } else {
                bail!("Failed to encode incoming NimbusProtocol data")
            }
        }
        // Note that this is just an error propagation, it might never be logged.
        // It is main thread's responsability to ensure main task's health
        Err(WorkerError::ErrReceiverChannelClosed).context("Messenger exited.")?
    })
}
